department_app/views/departments_views.py
"""
Module containing departments blueprint and functions
"""

from uuid import UUID

import requests
from flask import Blueprint, render_template, url_for


departments = Blueprint('departments', __name__, template_folder='templates')


@departments.route('/departments/', methods=['GET'])
def departments_view() -> str:
    """
    Renders and returns web page with all departments
    :return: rendered HTML page
    :rtype: str
    """
    response = requests.get(url_for('rest_api.departmentsapi', _external=True))
    departments_json = response.json()
    return render_template('departments.html', departments=departments_json)


@departments.route('/departments/add', methods=['GET'])
def departments_add() -> str:
    """
    Renders and returns web page used to add a department
    :return: rendered HTML page
    :rtype: str
    """
    return render_template('departments_add.html')


@departments.route('/departments/<uuid:department_id>/edit', methods=['GET'])
def departments_edit(department_id: UUID) -> str:
    """
    Renders and returns web page used to edit data of a department with specified id
    :param department_id: id of a department
    :type department_id: UUID
    :return: rendered HTML page
    :rtype: str
    """
    response = requests.get(url_for('rest_api.departmentapi', department_id=department_id, _external=True))
    department_json = response.json()
    return render_template('department_edit.html', department=department_json)

department_app/views/employees_views.py
"""
Module containing employees blueprint and functions
"""

from uuid import UUID

import requests
from flask import Blueprint, render_template, request, url_for

employees = Blueprint('employees', __name__, template_folder='templates')


@employees.route('/employees/', methods=['GET'])
def employees_view() -> str:
    """
    Renders and returns web page with employees that satisfy filtering options received from request args
    :return: rendered HTML page
    :rtype: str
    """
    request_data = request.args.to_dict()
    if request_data is not None:
        if 'department_id' in request_data and request_data['department_id']:
            department_id = request_data['department_id']
        else:
            department_id = None
        if 'start_date' in request_data and request_data['start_date']:
            start_date = request_data['start_date']
        else:
            start_date = None
        if 'end_date' in request_data and request_data['end_date']:
            end_date = request_data['end_date']
        else:
            end_date = None

        response = requests.get(url_for('rest_api.employeesapi', _external=True,
                                        department_id=department_id,
                                        start_date=start_date,
                                        end_date=end_date))
    else:
        response = requests.get(url_for('rest_api.employeesapi', _external=True))
    employees_json = response.json()
    response = requests.get(url_for('rest_api.departmentsapi', _external=True))
    departments_json = response.json()
    return render_template('employees.html', employees=employees_json, departments=departments_json)


@employees.route('/employees/add', methods=['GET'])
def employees_add() -> str:
    """
    Renders and returns web page used to add an employee
    :return: rendered HTML page
    :rtype: str
    """
    response = requests.get(url_for('rest_api.departmentsapi', _external=True))
    departments_json = response.json()
    return render_template('employees_add.html', departments=departments_json)


@employees.route('/employees/<uuid:employee_id>/edit', methods=['GET'])
def employees_edit(employee_id: UUID):
    """
    Renders and returns web page used to edit data of an employee with specified id
    :param employee_id: id of an employee
    :type employee_id: UUID
    :return: rendered HTML page
    :rtype: str
    """
    response = requests.get(url_for('rest_api.employeeapi', employee_id=employee_id, _external=True))
    employee_json = response.json()
    response = requests.get(url_for('rest_api.departmentsapi', _external=True))
    departments_json = response.json()
    return render_template('employee_edit.html', employee=employee_json, departments=departments_json)

department_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet"  href="{{ url_for('static', filename='style.css' ) }}">
    <title>{% block title %}{% endblock %}</title>
    {% block head %}{% endblock %}
</head>
<body>
    {% block body %}{% endblock %}
</body>
</html>

department_app/templates/department_edit.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
{% block title %}Edit department{% endblock %}
<body>
{% block body %}
    <div class="tab-bar">
        <a class="active-button button" href="{{ url_for('departments.departments_view') }}">Departments</a>
        <a class="button" href="{{ url_for('employees.employees_view') }}">Employees</a>
    </div>
    <div class="content">
        <div class="buttons-bar">
            <h1 class="department_header">Edit department</h1>

            <button class="save-button" onclick="edit_department()">Save</button>

            <a class="cancel-button" href="{{ url_for('departments.departments_view') }}">Cancel</a>
        </div>
        <div class="add-department-content">
            <form name="new_department" action="{{ url_for('rest_api.departmentsapi') }}" method="POST">
                <div class="input-line">
                    <p>Name</p>
                    <label>
                        <input name="department_name" type="text" value="{{ department.department_name }}">
                    </label>
                </div>
                <div class="input-line">
                    <p>Phone number</p>
                    <label>
                        <input name="department_phone_number" type="text" value="{{ department.department_phone_number }}">
                    </label>
                </div>
            </form>
        </div>
    </div>
    <script>
        function edit_department(){
            var data = new FormData(document.forms.new_department)
            var xhr = new XMLHttpRequest()
            xhr.open("PUT", "{{ url_for('rest_api.departmentapi', department_id=department.department_id) }}")
            xhr.send(data)
            window.location.replace("{{ url_for('departments.departments_view') }}")
        }
    </script>
{% endblock %}
</body>
</html>

department_app/templates/departments.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
{% block title %}Departments{% endblock %}
<body>
{% block body %}
    <div class="tab-bar">
        <a class="active-button button" href="{{ url_for('departments.departments_view') }}">Departments</a>
        <a class="button" href="{{ url_for('employees.employees_view') }}">Employees</a>
    </div>
    <div id="departments" class="content">
        <div class="buttons-bar">
            <a class="add-button" href="{{ url_for('departments.departments_add') }}">Add</a>
        </div>
        <div class="departments-content">
            <table class="departments-table">
                <tr class="table-header">
                    <th>Name</th>
                    <th>Employees count</th>
                    <th>Avg. salary</th>
                    <th>Phone number</th>
                    <th></th>
                </tr>
                {% for department in departments %}
                <tr class="table-content">
                    <td>{{ department.department_name }}</td>
                    <td>{{ department.number_of_employees }}</td>
                    <td>{{ department.average_salary }}</td>
                    <td>{{ department.department_phone_number }}</td>
                    <td>
                        <a class="edit-button" href="{{ url_for('departments.departments_edit', department_id=department.department_id) }}">Edit</a>
                        <button id="{{ url_for('rest_api.departmentapi', department_id=department.department_id) }}"  class="delete-button" onclick="delete_department(id)">Delete</button>
                    </td>
                </tr>
                {% endfor %}
            </table>
        </div>
    <script>
        function delete_department(url){
            if (confirm("Please confirm deletion of the department")) {
                let options = {
                    method: "DELETE"
                }
                fetch(url, options)
                document.location.reload()
            }
        }
    </script>
{% endblock %}
</body>
</html>

department_app/templates/departments_add.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
{% block title %}Add department{% endblock %}
<body>
{% block body %}
    <div class="tab-bar">
        <a class="active-button button" href="{{ url_for('departments.departments_view') }}">Departments</a>
        <a class="button" href="{{ url_for('employees.employees_view') }}">Employees</a>
    </div>
    <div id="add_department" class="content">
        <div class="buttons-bar">
            <h1 class="department_header">Add department</h1>

            <button class="save-button" onclick="add_department()">Save</button>

            <a class="cancel-button" href="{{ url_for('departments.departments_view') }}">Cancel</a>
        </div>
        <div class="add-department-content">
            <form name="new_department" action="{{ url_for('rest_api.departmentsapi') }}" method="POST">
                <div class="input-line">
                    <p>Name</p>
                    <label>
                        <input name="department_name" type="text">
                    </label>
                </div>
                <div class="input-line">
                    <p>Phone number</p>
                    <label>
                        <input name="department_phone_number" type="text">
                    </label>
                </div>
            </form>
        </div>
    </div>
    <script>
        function add_department(){
            var data = new FormData(document.forms.new_department)
            var xhr = new XMLHttpRequest()
            xhr.open("POST", "{{ url_for('rest_api.departmentsapi') }}")
            xhr.send(data)
            window.location.replace("{{ url_for('departments.departments_view') }}")
        }
    </script>
{% endblock %}
</body>
</html>

department_app/templates/employee_edit.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
{% block title %}Edit department{% endblock %}
<body>
{% block body %}
    <div class="tab-bar">
        <a class="button" href="{{ url_for('departments.departments_view') }}">Departments</a>
        <a class="active-button button" href="{{ url_for('employees.employees_view') }}">Employees</a>
    </div>
    <div class="content">
        <div class="buttons-bar">
            <h1 class="employee-header">Edit employee</h1>

            <button class="save-button" onclick="edit_employee()">Save</button>

            <a class="cancel-button" href="{{ url_for('employees.employees_view') }}">Cancel</a>
        </div>
        <div class="add-employee-content">
            <form name="new_employee" action="{{ url_for('rest_api.employeesapi') }}" method="POST">
                <div class="input-line">
                    <p>Name</p>
                    <label>
                        <input name="employee_name" type="text" value="{{ employee.employee_name }}">
                    </label>
                </div>
                <div class="input-line">
                    <p>Department</p>
                    <label>
                        <select name="department_id">
                            <option></option>
                            {% for department in departments %}
                            {% if department.department_id == employee.department_id %}
                            <option selected value="{{ department.department_id }}" >{{ department.department_name }}</option>
                            {% else %}
                            <option selected value="{{ department.department_id }}" >{{ department.department_name }}</option>
                            {% endif %}
                            {% endfor %}
                        </select>
                    </label>
                </div>
                <div class="input-line">
                    <p>Position</p>
                    <label>
                        <input name="position" type="text" value="{{ employee.position }}">
                    </label>
                </div>
                <div class="input-line">
                    <p>Salary</p>
                    <label>
                        <input name="salary" type="number" value="{{ employee.salary }}">
                    </label>
                </div>
                <div class="input-line">
                    <p>Birthdate</p>
                    <label>
                        <input name="birthdate" type="date" value="{{ employee.birthdate }}">
                    </label>
                </div>
            </form>
        </div>
    </div>
    <script>
        function edit_employee(){
            var data = new FormData(document.forms.new_employee)
            var xhr = new XMLHttpRequest()
            xhr.open("PUT", "{{ url_for('rest_api.employeeapi', employee_id=employee.employee_id) }}")
            xhr.send(data)
            window.location.replace("{{ url_for('employees.employees_view') }}")
        }
    </script>
{% endblock %}
</body>
</html>

department_app/templates/employees.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
{% block title %}Employees{% endblock %}
<body>
{% block body %}
    <div class="tab-bar">
        <a class="button" href="{{ url_for('departments.departments_view') }}">Departments</a>
        <a class="active-button button" href="{{ url_for('employees.employees_view') }}">Employees</a>
    </div>
    <div id="departments" class="content">
        <div class="buttons-bar">
            <a class="add-button" href="{{ url_for('employees.employees_add') }}">Add</a>
        </div>
        <div class="search-bar">
            <form class="search-inputs" name="employee_search" action="{{ url_for('employees.employees_view') }}" method="GET">
                <label>
                    <input name="start_date" type="date">
                </label>
                —
                <label>
                    <input name="end_date" type="date">
                </label>
                <label>
                    Department:
                    <select name="department_id">
                        <option selected></option>
                        {% for department in departments %}
                        <option value="{{ department.department_id }}" >{{ department.department_name }}</option>
                        {% endfor %}
                    </select>
                </label>
                <input type="submit" value="Search">

            </form>
        </div>
        <div class="departments-content">
            <table class="departments-table">
                <tr class="table-header">
                    <th>Name</th>
                    <th>Department</th>
                    <th>Position</th>
                    <th>Salary</th>
                    <th>Birthdate</th>
                    <th></th>
                </tr>
                {% for employee in employees %}
                <tr class="table-content">
                    <td>{{ employee.employee_name }}</td>
                    <td>{{ employee.department.department_name }}</td>
                    <td>{{ employee.position }}</td>
                    <td>{{ employee.salary }}</td>
                    <td>{{ employee.birthdate }}</td>
                    <td>
                        <a class="edit-button" href="{{ url_for('employees.employees_edit', employee_id=employee.employee_id) }}">Edit</a>
                        <button id="{{ url_for('rest_api.employeeapi', employee_id=employee.employee_id) }}"  class="delete-button" onclick="delete_department(id)">Delete</button>
                    </td>
                </tr>
                {% endfor %}
            </table>
        </div>
    <script>
        function delete_department(url){
            if (confirm("Please confirm deletion of the employee")) {
                let options = {
                    method: "DELETE"
                }
                fetch(url, options)
                document.location.reload()
            }
        }
    </script>
{% endblock %}
</body>
</html>

department_app/templates/employees_add.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
{% block title %}Add employee{% endblock %}
<body>
{% block body %}
    <div class="tab-bar">
        <a class="button" href="{{ url_for('departments.departments_view') }}">Departments</a>
        <a class="active-button button" href="{{ url_for('employees.employees_view') }}">Employees</a>
    </div>
    <div class="content">
        <div class="buttons-bar">
            <h1 class="employee-header">Add employee</h1>

            <button class="save-button" onclick="add_employee()">Save</button>

            <a class="cancel-button" href="{{ url_for('employees.employees_view') }}">Cancel</a>
        </div>
        <div class="add-employee-content">
            <form name="new_employee" action="{{ url_for('rest_api.employeesapi') }}" method="POST">
                <div class="input-line">
                    <p>Name</p>
                    <label>
                        <input name="employee_name" type="text">
                    </label>
                </div>
                <div class="input-line">
                    <p>Department</p>
                    <label>
                        <select name="department_id">
                            <option selected></option>
                            {% for department in departments %}
                            <option value="{{ department.department_id }}" >{{ department.department_name }}</option>
                            {% endfor %}
                        </select>
                    </label>
                </div>
                <div class="input-line">
                    <p>Position</p>
                    <label>
                        <input name="position" type="text">
                    </label>
                </div>
                <div class="input-line">
                    <p>Salary</p>
                    <label>
                        <input name="salary" type="number">
                    </label>
                </div>
                <div class="input-line">
                    <p>Birthdate</p>
                    <label>
                        <input name="birthdate" type="date">
                    </label>
                </div>
            </form>
        </div>
    </div>
    <script>
        function add_employee(){
            var data = new FormData(document.forms.new_employee)
            var xhr = new XMLHttpRequest()
            xhr.open("POST", "{{ url_for('rest_api.employeesapi') }}")
            xhr.send(data)
            window.location.replace("{{ url_for('employees.employees_view') }}")
        }
    </script>
{% endblock %}
</body>
</html>